/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: WorldwideCookie (https://sketchfab.com/WorldwideCookie)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/spirited-away-51e6f6a2816540b780bc0f1c82130a0b
Title: Spirited Away
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame, useThree } from '@react-three/fiber';
import { a } from '@react-spring/three';

import islandScene from '../assets/3d/spirited_away.glb';

const SpiritedAway = (props) => {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(islandScene)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}
    scale={[0.15, 0.15, 0.15]}
    position={[0, -1, 0]}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="2cf451f0841f492e897ae3d00ad516d5fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="pCube3" position={[0.005, 9.495, 6.844]} scale={[3.598, 5.56, 4.687]}>
                  <mesh
                    name="pCube3_Square_B1_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube3_Square_B1_0.geometry}
                    material={materials.Square_B1}
                  />
                </group>
                <group
                  name="pCube4"
                  position={[-0.028, 6.706, -5.542]}
                  scale={[11.138, 2.136, 4.64]}>
                  <mesh
                    name="pCube4_blinn13_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube4_blinn13_0.geometry}
                    material={materials.blinn13}
                  />
                </group>
                <group
                  name="pPlane3"
                  position={[0.012, 11.703, 5.24]}
                  rotation={[-2.492, 0, -Math.PI]}
                  scale={[9.767, 7.772, 7.591]}>
                  <mesh
                    name="pPlane3_blinn5_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pPlane3_blinn5_0.geometry}
                    material={materials.blinn5}
                  />
                </group>
                <group
                  name="pCylinder5"
                  position={[-7.336, 6.433, 3.461]}
                  rotation={[-0.045, 0, 0]}
                  scale={0.346}>
                  <mesh
                    name="pCylinder5_Brown_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCylinder5_Brown_0.geometry}
                    material={materials.Brown}
                  />
                </group>
                <group name="pCylinder6" position={[-0.537, 6.647, 3.061]} scale={0.353}>
                  <mesh
                    name="pCylinder6_Brown_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCylinder6_Brown_0.geometry}
                    material={materials.Brown}
                  />
                </group>
                <group name="pCylinder11" position={[-9.178, 1.971, -9.288]} scale={1.013}>
                  <mesh
                    name="pCylinder11_blinn2_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCylinder11_blinn2_0.geometry}
                    material={materials.blinn2}
                  />
                </group>
                <group name="pCube16" position={[0.165, 0, 0.002]} rotation={[0, -0.02, 0]}>
                  <mesh
                    name="pCube16_Plate_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube16_Plate_0.geometry}
                    material={materials.Plate}
                  />
                </group>
                <group
                  name="pCylinder12"
                  position={[5.105, 11.897, 2.412]}
                  rotation={[0, 0, Math.PI / 2]}>
                  <mesh
                    name="pCylinder12_Extra_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCylinder12_Extra_0.geometry}
                    material={materials.Extra}
                  />
                </group>
                <group name="pPlane4" position={[-0.029, 11.482, 5.121]} scale={8.787}>
                  <mesh
                    name="pPlane4_blinn6_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pPlane4_blinn6_0.geometry}
                    material={materials.blinn6}
                  />
                </group>
                <group name="pCube24" position={[-9.56, 5.319, -2.586]} scale={1.082}>
                  <mesh
                    name="pCube24_Brown_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube24_Brown_0.geometry}
                    material={materials.Brown}
                  />
                </group>
                <group
                  name="pCylinder16"
                  position={[-0.025, 13.218, 9.127]}
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.502}>
                  <mesh
                    name="pCylinder16_blinn13_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCylinder16_blinn13_0.geometry}
                    material={materials.blinn13}
                  />
                </group>
                <group name="pSphere2" position={[-0.035, 13.216, 9.235]} scale={0.251}>
                  <mesh
                    name="pSphere2_blinn13_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pSphere2_blinn13_0.geometry}
                    material={materials.blinn13}
                  />
                </group>
                <group name="pCylinder23">
                  <mesh
                    name="pCylinder23_blinn13_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCylinder23_blinn13_0.geometry}
                    material={materials.blinn13}
                  />
                </group>
                <group
                  name="pCylinder24"
                  position={[0, 14.715, 2.384]}
                  rotation={[0, 0, Math.PI / 2]}
                  scale={0.541}>
                  <mesh
                    name="pCylinder24_blinn13_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCylinder24_blinn13_0.geometry}
                    material={materials.blinn13}
                  />
                </group>
                <group
                  name="pCube31"
                  position={[0.007, 14.197, 2.395]}
                  scale={[1.259, 1.302, 1.302]}>
                  <mesh
                    name="pCube31_blinn13_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube31_blinn13_0.geometry}
                    material={materials.blinn13}
                  />
                </group>
                <group name="pPlane6" position={[-0.033, 0, 0.002]}>
                  <mesh
                    name="pPlane6_aiStandardSurface4_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pPlane6_aiStandardSurface4_0.geometry}
                    material={materials.aiStandardSurface4}
                  />
                  <mesh
                    name="pPlane6_Main_Terrace_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pPlane6_Main_Terrace_0.geometry}
                    material={materials.Main_Terrace}
                  />
                  <mesh
                    name="pPlane6_Terrace_C_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pPlane6_Terrace_C_0.geometry}
                    material={materials.Terrace_C}
                  />
                </group>
                <group
                  name="pCube36"
                  position={[-0.079, 13.004, 4.311]}
                  scale={[4.692, 2.967, 3.615]}>
                  <mesh
                    name="pCube36_Square_B_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube36_Square_B_0.geometry}
                    material={materials.Square_B}
                  />
                  <mesh
                    name="pCube36_lambert31_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube36_lambert31_0.geometry}
                    material={materials.lambert31}
                  />
                </group>
                <group
                  name="pCube37"
                  position={[-1.535, 9.734, -0.591]}
                  scale={[0.324, 0.717, 0.608]}>
                  <mesh
                    name="pCube37_Brown_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube37_Brown_0.geometry}
                    material={materials.Brown}
                  />
                </group>
                <group
                  name="pCube38"
                  position={[-4.361, 9.734, -0.591]}
                  scale={[0.324, 0.717, 0.608]}>
                  <mesh
                    name="pCube38_Brown_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube38_Brown_0.geometry}
                    material={materials.Brown}
                  />
                </group>
                <group name="pCube39" position={[2.199, 13.598, 5.395]} scale={[0.091, 0.46, 0.34]}>
                  <mesh
                    name="pCube39_Brown_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube39_Brown_0.geometry}
                    material={materials.Brown}
                  />
                </group>
                <group
                  name="pCube40"
                  position={[-2.364, 13.598, 5.395]}
                  rotation={[-Math.PI, 0, -Math.PI]}
                  scale={[0.091, 0.46, 0.34]}>
                  <mesh
                    name="pCube40_Brown_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube40_Brown_0.geometry}
                    material={materials.Brown}
                  />
                </group>
                <group
                  name="pPlane9"
                  position={[-0.06, 6.545, -8.289]}
                  rotation={[-1.131, 0, 0]}
                  scale={[13.399, 5.516, 2.651]}>
                  <mesh
                    name="pPlane9_blinn10_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pPlane9_blinn10_0.geometry}
                    material={materials.blinn10}
                  />
                </group>
                <group
                  name="pPlane10"
                  position={[5.614, 6.61, -8.282]}
                  rotation={[-Math.PI / 2, -0.526, -Math.PI / 2]}
                  scale={[9.916, 5.841, 2.897]}>
                  <mesh
                    name="pPlane10_blinn11_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pPlane10_blinn11_0.geometry}
                    material={materials.blinn11}
                  />
                </group>
                <group
                  name="pPlane11"
                  position={[-5.633, 6.618, -4.169]}
                  rotation={[-Math.PI / 2, 0.526, Math.PI / 2]}
                  scale={[9.916, 5.841, 2.897]}>
                  <mesh
                    name="pPlane11_blinn12_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pPlane11_blinn12_0.geometry}
                    material={materials.blinn12}
                  />
                </group>
                <group name="pCylinder32" position={[0.464, 0, 0]}>
                  <mesh
                    name="pCylinder32_blinn13_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCylinder32_blinn13_0.geometry}
                    material={materials.blinn13}
                  />
                </group>
                <group name="pCylinder33" position={[-8.423, 0, 0]}>
                  <mesh
                    name="pCylinder33_blinn13_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCylinder33_blinn13_0.geometry}
                    material={materials.blinn13}
                  />
                </group>
                <group
                  name="pCylinder34"
                  position={[8.677, -3.799, -8.949]}
                  rotation={[-2.487, 0, -Math.PI]}
                  scale={0.89}>
                  <mesh
                    name="pCylinder34_blinn13_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCylinder34_blinn13_0.geometry}
                    material={materials.blinn13}
                  />
                </group>
                <group
                  name="pCylinder35"
                  position={[-1.638, -3.799, -8.949]}
                  rotation={[-2.487, 0, -Math.PI]}
                  scale={0.89}>
                  <mesh
                    name="pCylinder35_blinn13_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCylinder35_blinn13_0.geometry}
                    material={materials.blinn13}
                  />
                </group>
                <group
                  name="pCylinder36"
                  position={[3.4, -3.801, -4.435]}
                  rotation={[-Math.PI / 2, 0.916, Math.PI / 2]}
                  scale={0.89}>
                  <mesh
                    name="pCylinder36_blinn13_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCylinder36_blinn13_0.geometry}
                    material={materials.blinn13}
                  />
                </group>
                <group name="pPlane12" position={[-0.025, 7.949, -5.535]} scale={8.115}>
                  <mesh
                    name="pPlane12_blinn9_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pPlane12_blinn9_0.geometry}
                    material={materials.blinn9}
                  />
                </group>
                <group
                  name="pCylinder37"
                  position={[7.048, 0.996, -3.274]}
                  rotation={[2.851, 0.573, 3.056]}
                  scale={[0.558, 0.558, 0.476]}>
                  <mesh
                    name="pCylinder37_blinn13_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCylinder37_blinn13_0.geometry}
                    material={materials.blinn13}
                  />
                </group>
                <group
                  name="pCylinder38"
                  position={[-7.782, 0.756, -2.503]}
                  rotation={[2.689, -0.11, -2.579]}
                  scale={[0.62, 0.62, 0.529]}>
                  <mesh
                    name="pCylinder38_blinn13_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCylinder38_blinn13_0.geometry}
                    material={materials.blinn13}
                  />
                </group>
                <group name="pSphere4" position={[5.17, 7.944, -7.985]} scale={0.393}>
                  <mesh
                    name="pSphere4_blinn13_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pSphere4_blinn13_0.geometry}
                    material={materials.blinn13}
                  />
                </group>
                <group name="pSphere5" position={[-5.277, 7.944, -8.014]} scale={0.393}>
                  <mesh
                    name="pSphere5_blinn13_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pSphere5_blinn13_0.geometry}
                    material={materials.blinn13}
                  />
                </group>
                <group
                  name="pCylinder39"
                  position={[-0.416, -0.061, 4.746]}
                  rotation={[-Math.PI, 0, -Math.PI]}>
                  <mesh
                    name="pCylinder39_blinn13_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCylinder39_blinn13_0.geometry}
                    material={materials.blinn13}
                  />
                </group>
                <group
                  name="pCylinder40"
                  position={[8.44, -0.061, 4.746]}
                  rotation={[-Math.PI, 0, -Math.PI]}>
                  <mesh
                    name="pCylinder40_blinn13_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCylinder40_blinn13_0.geometry}
                    material={materials.blinn13}
                  />
                </group>
                <group
                  name="pCube41"
                  position={[-0.066, 16.899, 4.618]}
                  scale={[2.699, 4.695, 2.652]}>
                  <mesh
                    name="pCube41_blinn7_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube41_blinn7_0.geometry}
                    material={materials.blinn7}
                  />
                </group>
                <group
                  name="pPlane14"
                  position={[-0.077, 14.44, 4.313]}
                  scale={[5.658, 4.479, 4.479]}>
                  <mesh
                    name="pPlane14_Brown_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pPlane14_Brown_0.geometry}
                    material={materials.Brown}
                  />
                </group>
                <group
                  name="pCube42"
                  position={[-0.08, 15.147, 6.48]}
                  scale={[5.678, 0.131, 0.202]}>
                  <mesh
                    name="pCube42_Brown_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube42_Brown_0.geometry}
                    material={materials.Brown}
                  />
                </group>
                <group
                  name="pCube43"
                  position={[2.672, 15.147, 4.307]}
                  rotation={[0, Math.PI / 2, 0]}
                  scale={[4.55, 0.142, 0.202]}>
                  <mesh
                    name="pCube43_Brown_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube43_Brown_0.geometry}
                    material={materials.Brown}
                  />
                </group>
                <group
                  name="pCube44"
                  position={[-2.824, 15.147, 4.307]}
                  rotation={[0, Math.PI / 2, 0]}
                  scale={[4.55, 0.148, 0.202]}>
                  <mesh
                    name="pCube44_Brown_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube44_Brown_0.geometry}
                    material={materials.Brown}
                  />
                </group>
                <group
                  name="pCube45"
                  position={[-0.08, 14.801, 6.484]}
                  scale={[5.425, 0.063, 0.068]}>
                  <mesh
                    name="pCube45_Brown_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube45_Brown_0.geometry}
                    material={materials.Brown}
                  />
                </group>
                <group
                  name="pCube46"
                  position={[2.663, 14.801, 4.327]}
                  rotation={[0, Math.PI / 2, 0]}
                  scale={[4.412, 0.063, 0.068]}>
                  <mesh
                    name="pCube46_Brown_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube46_Brown_0.geometry}
                    material={materials.Brown}
                  />
                </group>
                <group
                  name="pCube47"
                  position={[-2.823, 14.801, 4.327]}
                  rotation={[0, Math.PI / 2, 0]}
                  scale={[4.412, 0.063, 0.068]}>
                  <mesh
                    name="pCube47_Brown_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube47_Brown_0.geometry}
                    material={materials.Brown}
                  />
                </group>
                <group
                  name="pCube48"
                  position={[2.665, 14.682, 4.26]}
                  rotation={[-Math.PI, 0, Math.PI / 2]}
                  scale={[0.364, 0.063, 0.068]}>
                  <mesh
                    name="pCube48_Brown_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube48_Brown_0.geometry}
                    material={materials.Brown}
                  />
                </group>
                <group
                  name="pCube49"
                  position={[2.665, 14.682, 5.785]}
                  rotation={[-Math.PI, 0, Math.PI / 2]}
                  scale={[0.364, 0.063, 0.068]}>
                  <mesh
                    name="pCube49_Brown_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube49_Brown_0.geometry}
                    material={materials.Brown}
                  />
                </group>
                <group
                  name="pCube50"
                  position={[-2.823, 14.687, 4.26]}
                  rotation={[-Math.PI, 0, Math.PI / 2]}
                  scale={[0.342, 0.063, 0.068]}>
                  <mesh
                    name="pCube50_Brown_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube50_Brown_0.geometry}
                    material={materials.Brown}
                  />
                </group>
                <group
                  name="pCube51"
                  position={[-2.823, 14.687, 5.785]}
                  rotation={[-Math.PI, 0, Math.PI / 2]}
                  scale={[0.342, 0.063, 0.068]}>
                  <mesh
                    name="pCube51_Brown_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube51_Brown_0.geometry}
                    material={materials.Brown}
                  />
                </group>
                <group
                  name="pCube52"
                  position={[-2.143, 14.699, 6.484]}
                  rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                  scale={[0.316, 0.063, 0.068]}>
                  <mesh
                    name="pCube52_Brown_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube52_Brown_0.geometry}
                    material={materials.Brown}
                  />
                </group>
                <group
                  name="pCube53"
                  position={[-0.799, 14.699, 6.484]}
                  rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                  scale={[0.316, 0.063, 0.068]}>
                  <mesh
                    name="pCube53_Brown_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube53_Brown_0.geometry}
                    material={materials.Brown}
                  />
                </group>
                <group
                  name="pCube54"
                  position={[0.593, 14.699, 6.484]}
                  rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                  scale={[0.316, 0.063, 0.068]}>
                  <mesh
                    name="pCube54_Brown_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube54_Brown_0.geometry}
                    material={materials.Brown}
                  />
                </group>
                <group
                  name="pCube55"
                  position={[2.027, 14.699, 6.484]}
                  rotation={[-Math.PI / 2, Math.PI / 2, 0]}
                  scale={[0.316, 0.063, 0.068]}>
                  <mesh
                    name="pCube55_Brown_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube55_Brown_0.geometry}
                    material={materials.Brown}
                  />
                </group>
                <group
                  name="pCube56"
                  position={[2.02, 14.259, 6.234]}
                  scale={[0.127, 0.374, 0.408]}>
                  <mesh
                    name="pCube56_Brown_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube56_Brown_0.geometry}
                    material={materials.Brown}
                  />
                </group>
                <group
                  name="pCube57"
                  position={[1.313, 14.259, 6.234]}
                  scale={[0.127, 0.374, 0.408]}>
                  <mesh
                    name="pCube57_Brown_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube57_Brown_0.geometry}
                    material={materials.Brown}
                  />
                </group>
                <group
                  name="pCube58"
                  position={[0.594, 14.259, 6.234]}
                  scale={[0.127, 0.374, 0.408]}>
                  <mesh
                    name="pCube58_Brown_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube58_Brown_0.geometry}
                    material={materials.Brown}
                  />
                </group>
                <group
                  name="pCube59"
                  position={[-0.147, 14.259, 6.234]}
                  scale={[0.127, 0.374, 0.408]}>
                  <mesh
                    name="pCube59_Brown_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube59_Brown_0.geometry}
                    material={materials.Brown}
                  />
                </group>
                <group
                  name="pCube60"
                  position={[-0.795, 14.259, 6.234]}
                  scale={[0.127, 0.374, 0.408]}>
                  <mesh
                    name="pCube60_Brown_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube60_Brown_0.geometry}
                    material={materials.Brown}
                  />
                </group>
                <group
                  name="pCube61"
                  position={[-1.479, 14.259, 6.234]}
                  scale={[0.127, 0.374, 0.408]}>
                  <mesh
                    name="pCube61_Brown_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube61_Brown_0.geometry}
                    material={materials.Brown}
                  />
                </group>
                <group
                  name="pCube62"
                  position={[-2.153, 14.259, 6.234]}
                  scale={[0.127, 0.374, 0.408]}>
                  <mesh
                    name="pCube62_Brown_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube62_Brown_0.geometry}
                    material={materials.Brown}
                  />
                </group>
                <group
                  name="pCube63"
                  position={[-2.532, 14.259, 5.797]}
                  rotation={[0, -Math.PI / 2, 0]}
                  scale={[0.127, 0.374, 0.408]}>
                  <mesh
                    name="pCube63_Brown_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube63_Brown_0.geometry}
                    material={materials.Brown}
                  />
                </group>
                <group
                  name="pCube64"
                  position={[-2.532, 14.259, 5.073]}
                  rotation={[0, -Math.PI / 2, 0]}
                  scale={[0.127, 0.374, 0.408]}>
                  <mesh
                    name="pCube64_Brown_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube64_Brown_0.geometry}
                    material={materials.Brown}
                  />
                </group>
                <group
                  name="pCube65"
                  position={[-2.532, 14.259, 4.264]}
                  rotation={[0, -Math.PI / 2, 0]}
                  scale={[0.127, 0.374, 0.408]}>
                  <mesh
                    name="pCube65_Brown_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube65_Brown_0.geometry}
                    material={materials.Brown}
                  />
                </group>
                <group
                  name="pCube66"
                  position={[-2.532, 14.259, 3.459]}
                  rotation={[0, -Math.PI / 2, 0]}
                  scale={[0.127, 0.374, 0.408]}>
                  <mesh
                    name="pCube66_Brown_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube66_Brown_0.geometry}
                    material={materials.Brown}
                  />
                </group>
                <group
                  name="pCube67"
                  position={[2.354, 14.259, 3.459]}
                  rotation={[Math.PI / 2, 0, Math.PI / 2]}
                  scale={[0.127, 0.374, 0.408]}>
                  <mesh
                    name="pCube67_Brown_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube67_Brown_0.geometry}
                    material={materials.Brown}
                  />
                </group>
                <group
                  name="pCube68"
                  position={[2.354, 14.259, 4.264]}
                  rotation={[Math.PI / 2, 0, Math.PI / 2]}
                  scale={[0.127, 0.374, 0.408]}>
                  <mesh
                    name="pCube68_Brown_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube68_Brown_0.geometry}
                    material={materials.Brown}
                  />
                </group>
                <group
                  name="pCube69"
                  position={[2.354, 14.259, 5.073]}
                  rotation={[Math.PI / 2, 0, Math.PI / 2]}
                  scale={[0.127, 0.374, 0.408]}>
                  <mesh
                    name="pCube69_Brown_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube69_Brown_0.geometry}
                    material={materials.Brown}
                  />
                </group>
                <group
                  name="pCube70"
                  position={[2.354, 14.259, 5.797]}
                  rotation={[Math.PI / 2, 0, Math.PI / 2]}
                  scale={[0.127, 0.374, 0.408]}>
                  <mesh
                    name="pCube70_Brown_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube70_Brown_0.geometry}
                    material={materials.Brown}
                  />
                </group>
                <group name="pCube71" position={[0.828, 17.704, 4.621]} scale={[0.096, 0.5, 0.5]}>
                  <mesh
                    name="pCube71_blinn13_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube71_blinn13_0.geometry}
                    material={materials.blinn13}
                  />
                </group>
                <group
                  name="pCube72"
                  position={[-0.971, 17.704, 4.621]}
                  rotation={[-Math.PI, 0, -Math.PI]}
                  scale={[0.096, 0.5, 0.5]}>
                  <mesh
                    name="pCube72_blinn13_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube72_blinn13_0.geometry}
                    material={materials.blinn13}
                  />
                </group>
                <group name="pPlane15" position={[-0.059, 21.956, 4.604]} scale={4.492}>
                  <mesh
                    name="pPlane15_CT_RT_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pPlane15_CT_RT_0.geometry}
                    material={materials.CT_RT}
                  />
                </group>
                <group
                  name="pCone1"
                  position={[-0.057, 25.236, 4.603]}
                  rotation={[0, -0.782, 0]}
                  scale={2.868}>
                  <mesh
                    name="pCone1_phong2_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCone1_phong2_0.geometry}
                    material={materials.phong2}
                  />
                  <mesh
                    name="pCone1_blinn8_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCone1_blinn8_0.geometry}
                    material={materials.blinn8}
                  />
                </group>
                <group name="pSphere6" position={[-0.059, 26.131, 4.59]} scale={0.221}>
                  <mesh
                    name="pSphere6_phong2_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pSphere6_phong2_0.geometry}
                    material={materials.phong2}
                  />
                </group>
                <group name="pCone2" position={[-0.052, 27.547, 4.602]}>
                  <mesh
                    name="pCone2_phong2_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCone2_phong2_0.geometry}
                    material={materials.phong2}
                  />
                </group>
                <group name="pCube78">
                  <mesh
                    name="pCube78_Main_Building_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube78_Main_Building_0.geometry}
                    material={materials.Main_Building}
                  />
                  <mesh
                    name="pCube78_lambert33_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube78_lambert33_0.geometry}
                    material={materials.lambert33}
                  />
                </group>
                <group name="pCube79" position={[0, 4.801, -8.031]} scale={[6.707, 1.718, 0.823]}>
                  <mesh
                    name="pCube79_Back_Terrace_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube79_Back_Terrace_0.geometry}
                    material={materials.Back_Terrace}
                  />
                </group>
                <group name="pCube101" position={[0, 0, 0.007]}>
                  <mesh
                    name="pCube101_Brown_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube101_Brown_0.geometry}
                    material={materials.Brown}
                  />
                </group>
                <group
                  name="pCube102"
                  position={[-0.015, 3.716, -8.204]}
                  scale={[0.174, 0.289, 1.175]}>
                  <mesh
                    name="pCube102_Brown_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube102_Brown_0.geometry}
                    material={materials.Brown}
                  />
                </group>
                <group
                  name="pCube103"
                  position={[-1.126, 3.716, -8.204]}
                  scale={[0.174, 0.289, 1.175]}>
                  <mesh
                    name="pCube103_Brown_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube103_Brown_0.geometry}
                    material={materials.Brown}
                  />
                </group>
                <group
                  name="pCube104"
                  position={[1.107, 3.716, -8.204]}
                  scale={[0.174, 0.289, 1.175]}>
                  <mesh
                    name="pCube104_Brown_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube104_Brown_0.geometry}
                    material={materials.Brown}
                  />
                </group>
                <group
                  name="pCube105"
                  position={[-2.235, 3.716, -8.204]}
                  scale={[0.174, 0.289, 1.175]}>
                  <mesh
                    name="pCube105_Brown_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube105_Brown_0.geometry}
                    material={materials.Brown}
                  />
                </group>
                <group
                  name="pCube106"
                  position={[-3.457, 3.716, -8.204]}
                  scale={[0.174, 0.289, 1.175]}>
                  <mesh
                    name="pCube106_Brown_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube106_Brown_0.geometry}
                    material={materials.Brown}
                  />
                </group>
                <group
                  name="pCube107"
                  position={[2.225, 3.716, -8.204]}
                  scale={[0.174, 0.289, 1.175]}>
                  <mesh
                    name="pCube107_Brown_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube107_Brown_0.geometry}
                    material={materials.Brown}
                  />
                </group>
                <group
                  name="pCube108"
                  position={[3.458, 3.716, -8.204]}
                  scale={[0.174, 0.289, 1.175]}>
                  <mesh
                    name="pCube108_Brown_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube108_Brown_0.geometry}
                    material={materials.Brown}
                  />
                </group>
                <group
                  name="pCube109"
                  position={[1.507, 6.254, 8.442]}
                  scale={[0.341, 0.98, 0.964]}>
                  <mesh
                    name="pCube109_Small_Thingies_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube109_Small_Thingies_0.geometry}
                    material={materials.Small_Thingies}
                  />
                </group>
                <group name="pPlane16" scale={29.256}>
                  <mesh
                    name="pPlane16_Ground_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pPlane16_Ground_0.geometry}
                    material={materials.Ground}
                  />
                  <mesh
                    name="pPlane16_blinn13_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pPlane16_blinn13_0.geometry}
                    material={materials.blinn13}
                  />
                </group>
                <group
                  name="pSphere7"
                  position={[6.89, 0.906, 7.442]}
                  rotation={[0, -0.303, -0.697]}
                  scale={[1.098, 1.376, 1.011]}>
                  <mesh
                    name="pSphere7_blinn1_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pSphere7_blinn1_0.geometry}
                    material={materials.blinn1}
                  />
                </group>
                <group
                  name="pSphere8"
                  position={[11.257, -0.139, 9.456]}
                  rotation={[-1.723, -0.28, -1.102]}
                  scale={[1.102, 1.827, 1.015]}>
                  <mesh
                    name="pSphere8_blinn1_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pSphere8_blinn1_0.geometry}
                    material={materials.blinn1}
                  />
                </group>
                <group
                  name="pSphere9"
                  position={[-11.068, -0.644, 7.442]}
                  rotation={[0.632, -0.56, 1.864]}
                  scale={[1.604, 1.596, 1.011]}>
                  <mesh
                    name="pSphere9_blinn1_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pSphere9_blinn1_0.geometry}
                    material={materials.blinn1}
                  />
                </group>
                <group
                  name="pSphere10"
                  position={[-8.967, -0.626, 9.967]}
                  rotation={[-0.814, -0.093, -0.563]}
                  scale={[0.644, 0.64, 0.406]}>
                  <mesh
                    name="pSphere10_blinn1_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pSphere10_blinn1_0.geometry}
                    material={materials.blinn1}
                  />
                </group>
                <group name="pCube116" position={[0, -0.036, 8.252]} scale={[1.592, 0.238, 1.276]}>
                  <mesh
                    name="pCube116_blinn1_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube116_blinn1_0.geometry}
                    material={materials.blinn1}
                  />
                </group>
                <group name="pCube117" position={[0, -0.139, 9.026]} scale={[1.592, 0.213, 0.385]}>
                  <mesh
                    name="pCube117_blinn1_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube117_blinn1_0.geometry}
                    material={materials.blinn1}
                  />
                </group>
                <group name="pCube118" position={[0, -0.254, 9.409]} scale={[1.592, 0.186, 0.385]}>
                  <mesh
                    name="pCube118_blinn1_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube118_blinn1_0.geometry}
                    material={materials.blinn1}
                  />
                </group>
                <group name="pCube119" position={[0, -0.378, 9.787]} scale={[1.592, 0.171, 0.385]}>
                  <mesh
                    name="pCube119_blinn1_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube119_blinn1_0.geometry}
                    material={materials.blinn1}
                  />
                </group>
                <group name="pCube120" position={[0, -0.509, 10.162]} scale={[1.592, 0.18, 0.385]}>
                  <mesh
                    name="pCube120_blinn1_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube120_blinn1_0.geometry}
                    material={materials.blinn1}
                  />
                </group>
                <group name="pCube121" position={[0, -0.624, 10.541]} scale={[1.592, 0.174, 0.385]}>
                  <mesh
                    name="pCube121_blinn1_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube121_blinn1_0.geometry}
                    material={materials.blinn1}
                  />
                </group>
                <group name="pCube122" position={[0, -0.731, 10.922]} scale={[1.592, 0.158, 0.385]}>
                  <mesh
                    name="pCube122_blinn1_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube122_blinn1_0.geometry}
                    material={materials.blinn1}
                  />
                </group>
                <group name="pCube123" position={[0, -0.848, 11.299]} scale={[1.592, 0.162, 0.385]}>
                  <mesh
                    name="pCube123_blinn1_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube123_blinn1_0.geometry}
                    material={materials.blinn1}
                  />
                </group>
                <group name="pCube124" position={[0, -0.967, 11.674]} scale={[1.592, 0.174, 0.385]}>
                  <mesh
                    name="pCube124_blinn1_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube124_blinn1_0.geometry}
                    material={materials.blinn1}
                  />
                </group>
                <group name="pCube125" position={[0, -1.072, 12.06]} scale={[1.592, 0.162, 0.385]}>
                  <mesh
                    name="pCube125_blinn1_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube125_blinn1_0.geometry}
                    material={materials.blinn1}
                  />
                </group>
                <group name="pCube126" position={[0, -1.17, 12.432]} scale={[1.592, 0.141, 0.385]}>
                  <mesh
                    name="pCube126_blinn1_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube126_blinn1_0.geometry}
                    material={materials.blinn1}
                  />
                </group>
                <group name="pCube127" position={[0, -1.28, 12.812]} scale={[1.592, 0.163, 0.385]}>
                  <mesh
                    name="pCube127_blinn1_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube127_blinn1_0.geometry}
                    material={materials.blinn1}
                  />
                </group>
                <group name="pCube128" position={[0, -1.372, 13.191]} scale={[1.592, 0.141, 0.385]}>
                  <mesh
                    name="pCube128_blinn1_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube128_blinn1_0.geometry}
                    material={materials.blinn1}
                  />
                </group>
                <group name="pCube129" position={[0, -1.479, 13.569]} scale={[1.592, 0.141, 0.385]}>
                  <mesh
                    name="pCube129_blinn1_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube129_blinn1_0.geometry}
                    material={materials.blinn1}
                  />
                </group>
                <group name="pCube130" position={[0, -1.581, 13.947]} scale={[1.592, 0.141, 0.385]}>
                  <mesh
                    name="pCube130_blinn1_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube130_blinn1_0.geometry}
                    material={materials.blinn1}
                  />
                </group>
                <group name="pCube131" position={[0, -1.671, 14.33]} scale={[1.592, 0.162, 0.385]}>
                  <mesh
                    name="pCube131_blinn1_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube131_blinn1_0.geometry}
                    material={materials.blinn1}
                  />
                </group>
                <group name="pDisc1" position={[-0.002, -2.706, 0]} scale={19.361}>
                  <mesh
                    name="pDisc1_Water_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pDisc1_Water_0.geometry}
                    material={materials.Water}
                  />
                </group>
                <group name="pSphere13" position={[0, -0.073, 1.091]} scale={[1.095, 1.095, 1.034]}>
                  <mesh
                    name="pSphere13_Statue_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pSphere13_Statue_0.geometry}
                    material={materials.Statue}
                  />
                </group>
                <group
                  name="pSphere14"
                  position={[7.403, 9.861, -12.291]}
                  rotation={[-Math.PI, 0.725, -Math.PI]}
                  scale={[3.615, 3.76, 3.69]}>
                  <mesh
                    name="pSphere14_Tree_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pSphere14_Tree_0.geometry}
                    material={materials.Tree}
                  />
                </group>
                <group
                  name="pSphere15"
                  position={[-8.371, 9.861, -11.289]}
                  rotation={[0, -0.136, 0]}
                  scale={[3.615, 3.76, 3.69]}>
                  <mesh
                    name="pSphere15_Tree_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pSphere15_Tree_0.geometry}
                    material={materials.Tree}
                  />
                </group>
                <group
                  name="pCylinder45"
                  position={[7.493, 4.05, -12.356]}
                  scale={[0.659, 1.737, 0.659]}>
                  <mesh
                    name="pCylinder45_Brown_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCylinder45_Brown_0.geometry}
                    material={materials.Brown}
                  />
                </group>
                <group
                  name="pCylinder46"
                  position={[-8.291, 4.05, -11.354]}
                  rotation={[-Math.PI, 1.41, -Math.PI]}
                  scale={[0.659, 1.737, 0.659]}>
                  <mesh
                    name="pCylinder46_Brown_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCylinder46_Brown_0.geometry}
                    material={materials.Brown}
                  />
                </group>
                <group
                  name="pSphere16"
                  position={[-11.505, 7.148, -5.944]}
                  rotation={[-Math.PI, 1.496, -Math.PI]}
                  scale={[3.04, 3.161, 3.102]}>
                  <mesh
                    name="pSphere16_Tree_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pSphere16_Tree_0.geometry}
                    material={materials.Tree}
                  />
                </group>
                <group
                  name="pCylinder47"
                  position={[-11.418, 2.327, -5.947]}
                  rotation={[0, -1.156, 0]}
                  scale={[0.598, 1.802, 0.598]}>
                  <mesh
                    name="pCylinder47_Brown_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCylinder47_Brown_0.geometry}
                    material={materials.Brown}
                  />
                </group>
                <group
                  name="pSphere17"
                  position={[12.094, 7.378, -8.533]}
                  rotation={[0, -0.821, 0]}
                  scale={[3.04, 3.161, 3.102]}>
                  <mesh
                    name="pSphere17_Tree_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pSphere17_Tree_0.geometry}
                    material={materials.Tree}
                  />
                </group>
                <group
                  name="pCylinder48"
                  position={[12.181, 2.558, -8.536]}
                  rotation={[-Math.PI, 0.481, -Math.PI]}
                  scale={[0.598, 1.802, 0.598]}>
                  <mesh
                    name="pCylinder48_Brown_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCylinder48_Brown_0.geometry}
                    material={materials.Brown}
                  />
                </group>
                <group
                  name="pCylinder49"
                  position={[4.446, 14.958, 2.385]}
                  rotation={[1.561, 0, -Math.PI / 2]}
                  scale={[1.262, 1.998, 1.174]}>
                  <mesh
                    name="pCylinder49_blinn13_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCylinder49_blinn13_0.geometry}
                    material={materials.blinn13}
                  />
                </group>
                <group
                  name="pSphere18"
                  position={[4.949, 14.816, 2.407]}
                  scale={[0.75, 0.825, 0.78]}>
                  <mesh
                    name="pSphere18_blinn13_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pSphere18_blinn13_0.geometry}
                    material={materials.blinn13}
                  />
                </group>
                <group
                  name="pCylinder50"
                  position={[5.129, 16.089, 2.097]}
                  rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                  scale={[0.117, 0.948, 0.117]}>
                  <mesh
                    name="pCylinder50_blinn13_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCylinder50_blinn13_0.geometry}
                    material={materials.blinn13}
                  />
                </group>
                <group
                  name="pCube132"
                  position={[4.441, 16.116, 2.44]}
                  scale={[1.23, 0.435, 1.121]}>
                  <mesh
                    name="pCube132_blinn13_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube132_blinn13_0.geometry}
                    material={materials.blinn13}
                  />
                </group>
                <group
                  name="pCylinder53"
                  position={[5.129, 16.089, 2.443]}
                  rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                  scale={[0.117, 0.948, 0.117]}>
                  <mesh
                    name="pCylinder53_blinn13_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCylinder53_blinn13_0.geometry}
                    material={materials.blinn13}
                  />
                </group>
                <group
                  name="pCylinder54"
                  position={[5.129, 16.089, 2.791]}
                  rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                  scale={[0.117, 0.948, 0.117]}>
                  <mesh
                    name="pCylinder54_blinn13_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCylinder54_blinn13_0.geometry}
                    material={materials.blinn13}
                  />
                </group>
                <group
                  name="pCylinder55"
                  position={[-4.432, 14.958, 2.358]}
                  rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                  scale={[1.262, 1.998, 1.174]}>
                  <mesh
                    name="pCylinder55_blinn13_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCylinder55_blinn13_0.geometry}
                    material={materials.blinn13}
                  />
                </group>
                <group
                  name="pSphere19"
                  position={[-4.912, 14.816, 2.38]}
                  rotation={[-Math.PI, 0, -Math.PI]}
                  scale={[0.75, 0.825, 0.78]}>
                  <mesh
                    name="pSphere19_blinn13_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pSphere19_blinn13_0.geometry}
                    material={materials.blinn13}
                  />
                </group>
                <group
                  name="pCube133"
                  position={[-4.443, 16.116, 2.44]}
                  scale={[1.23, 0.435, 1.121]}>
                  <mesh
                    name="pCube133_blinn13_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube133_blinn13_0.geometry}
                    material={materials.blinn13}
                  />
                </group>
                <group
                  name="pCylinder56"
                  position={[-5.029, 16.089, 2.791]}
                  rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                  scale={[0.117, 0.948, 0.117]}>
                  <mesh
                    name="pCylinder56_blinn13_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCylinder56_blinn13_0.geometry}
                    material={materials.blinn13}
                  />
                </group>
                <group
                  name="pCylinder57"
                  position={[-5.029, 16.089, 2.443]}
                  rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                  scale={[0.117, 0.948, 0.117]}>
                  <mesh
                    name="pCylinder57_blinn13_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCylinder57_blinn13_0.geometry}
                    material={materials.blinn13}
                  />
                </group>
                <group
                  name="pCylinder58"
                  position={[-5.029, 16.089, 2.097]}
                  rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                  scale={[0.117, 0.948, 0.117]}>
                  <mesh
                    name="pCylinder58_blinn13_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCylinder58_blinn13_0.geometry}
                    material={materials.blinn13}
                  />
                </group>
                <group
                  name="pSphere20"
                  position={[11.581, 1.25, -7.016]}
                  rotation={[-0.464, 0.278, -0.225]}
                  scale={[1.372, 0.903, 1.138]}>
                  <mesh
                    name="pSphere20_Bush_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pSphere20_Bush_0.geometry}
                    material={materials.Bush}
                  />
                </group>
                <group
                  name="pSphere21"
                  position={[8.82, 2.791, -11.052]}
                  rotation={[-3.011, 0.088, -3.118]}
                  scale={[1.615, 0.917, 0.791]}>
                  <mesh
                    name="pSphere21_Bush_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pSphere21_Bush_0.geometry}
                    material={materials.Bush}
                  />
                </group>
                <group
                  name="pSphere22"
                  position={[12.927, 0.437, -5.924]}
                  rotation={[-3.011, 0.088, -3.118]}
                  scale={[0.849, 0.917, 0.554]}>
                  <mesh
                    name="pSphere22_Bush_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pSphere22_Bush_0.geometry}
                    material={materials.Bush}
                  />
                </group>
                <group
                  name="pSphere23"
                  position={[5.951, 1.89, -6.774]}
                  rotation={[-1.031, 1.419, 1.061]}
                  scale={[1.615, 0.917, 0.791]}>
                  <mesh
                    name="pSphere23_Bush_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pSphere23_Bush_0.geometry}
                    material={materials.Bush}
                  />
                </group>
                <group
                  name="pSphere24"
                  position={[5.877, 2.32, -12.412]}
                  rotation={[-3.02, -0.099, 1.897]}
                  scale={[0.849, 0.917, 0.791]}>
                  <mesh
                    name="pSphere24_Bush_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pSphere24_Bush_0.geometry}
                    material={materials.Bush}
                  />
                </group>
                <group
                  name="pSphere25"
                  position={[-6.036, 1.89, -6.774]}
                  rotation={[-2.497, -1.353, -2.473]}
                  scale={[1.615, 0.917, 0.791]}>
                  <mesh
                    name="pSphere25_Bush_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pSphere25_Bush_0.geometry}
                    material={materials.Bush}
                  />
                </group>
                <group
                  name="pSphere26"
                  position={[-6.406, 2.32, -11.931]}
                  rotation={[-0.122, -0.077, -1.266]}
                  scale={[0.849, 0.917, 0.791]}>
                  <mesh
                    name="pSphere26_Bush_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pSphere26_Bush_0.geometry}
                    material={materials.Bush}
                  />
                </group>
                <group
                  name="pSphere27"
                  position={[-8.981, 2.41, -10.521]}
                  rotation={[-0.206, -0.146, -0.265]}
                  scale={[1.615, 0.917, 0.791]}>
                  <mesh
                    name="pSphere27_Bush_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pSphere27_Bush_0.geometry}
                    material={materials.Bush}
                  />
                </group>
                <group
                  name="pSphere28"
                  position={[-10.602, 1.392, -3.965]}
                  rotation={[-2.652, -0.412, 2.99]}
                  scale={[1.372, 0.903, 1.138]}>
                  <mesh
                    name="pSphere28_Bush_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pSphere28_Bush_0.geometry}
                    material={materials.Bush}
                  />
                </group>
                <group
                  name="pSphere29"
                  position={[-12.064, 0.834, -2.873]}
                  rotation={[-3.011, 0.088, -3.118]}
                  scale={[0.849, 0.917, 0.554]}>
                  <mesh
                    name="pSphere29_Bush_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pSphere29_Bush_0.geometry}
                    material={materials.Bush}
                  />
                </group>
                <group
                  name="pSphere30"
                  position={[-2.973, 0.435, -13.089]}
                  rotation={[0.783, -0.269, 2.231]}
                  scale={[0.304, 0.303, 0.192]}>
                  <mesh
                    name="pSphere30_blinn1_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pSphere30_blinn1_0.geometry}
                    material={materials.blinn1}
                  />
                </group>
                <group
                  name="pSphere31"
                  position={[2.336, 0.018, -11.141]}
                  rotation={[0.429, 1.122, -0.529]}
                  scale={[0.259, 0.258, 0.163]}>
                  <mesh
                    name="pSphere31_blinn1_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pSphere31_blinn1_0.geometry}
                    material={materials.blinn1}
                  />
                </group>
                <group
                  name="pSphere32"
                  position={[2.673, 0.292, -11.609]}
                  rotation={[-1.367, -Math.PI / 8, 0.859]}
                  scale={[0.259, 0.258, 0.163]}>
                  <mesh
                    name="pSphere32_blinn1_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pSphere32_blinn1_0.geometry}
                    material={materials.blinn1}
                  />
                </group>
                <group
                  name="pSphere33"
                  position={[4.44, 1.16, -8.08]}
                  rotation={[-2.985, 0.013, 2.662]}
                  scale={[1.238, 0.84, 0.554]}>
                  <mesh
                    name="pSphere33_Bush_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pSphere33_Bush_0.geometry}
                    material={materials.Bush}
                  />
                </group>
                <group
                  name="pSphere34"
                  position={[-4.409, 1.16, -8.08]}
                  rotation={[-0.157, 0.005, -0.477]}
                  scale={[1.238, 0.84, 0.554]}>
                  <mesh
                    name="pSphere34_Bush_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pSphere34_Bush_0.geometry}
                    material={materials.Bush}
                  />
                </group>
                <group
                  name="directionalLight1"
                  position={[21.052, 21.184, 19.713]}
                  rotation={[0.883, 0.368, -0.775]}
                  scale={2.047}>
                  <group name="Object_295" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_296" />
                  </group>
                </group>
                <group
                  name="directionalLight2"
                  position={[-14.157, 22.574, -29.181]}
                  rotation={[-0.924, 0.2, 0.076]}
                  scale={2.833}>
                  <group name="Object_298" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_299" />
                  </group>
                </group>
                <group
                  name="directionalLight3"
                  position={[-42.039, 10.202, 19.834]}
                  rotation={[1.812, -0.62, 0.975]}
                  scale={2.361}>
                  <group name="Object_301" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_302" />
                  </group>
                </group>
                <group name="left" position={[0.16, 7.436, 72.1]} rotation={[0, 1.557, 0.031]}>
                  <group name="Object_304" />
                </group>
                <group
                  name="pPlane17"
                  position={[0.012, 11.703, -0.452]}
                  rotation={[-0.65, 0, 0]}
                  scale={[9.767, 7.772, 7.591]}>
                  <mesh
                    name="pPlane17_blinn5_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pPlane17_blinn5_0.geometry}
                    material={materials.blinn5}
                  />
                </group>
                <group
                  name="pPlane18"
                  position={[0.031, 0, -0.849]}
                  rotation={[-Math.PI, 0, -Math.PI]}>
                  <mesh
                    name="pPlane18_aiStandardSurface4_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pPlane18_aiStandardSurface4_0.geometry}
                    material={materials.aiStandardSurface4}
                  />
                  <mesh
                    name="pPlane18_Main_Terrace_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pPlane18_Main_Terrace_0.geometry}
                    material={materials.Main_Terrace}
                  />
                  <mesh
                    name="pPlane18_Terrace_C_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pPlane18_Terrace_C_0.geometry}
                    material={materials.Terrace_C}
                  />
                </group>
                <group
                  name="pCylinder59"
                  position={[-5.17, 11.897, 2.412]}
                  rotation={[-Math.PI, 0, -Math.PI / 2]}>
                  <mesh
                    name="pCylinder59_Extra_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCylinder59_Extra_0.geometry}
                    material={materials.Extra}
                  />
                </group>
                <group
                  name="pCylinder60"
                  position={[-6.634, 16.181, -5.301]}
                  scale={[0.725, 0.725, 0.617]}>
                  <mesh
                    name="pCylinder60_blinn3_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCylinder60_blinn3_0.geometry}
                    material={materials.blinn3}
                  />
                </group>
                <group
                  name="pCylinder61"
                  position={[6.491, 16.181, 14.544]}
                  rotation={[-Math.PI, 0, -Math.PI]}
                  scale={[0.725, 0.725, 0.617]}>
                  <mesh
                    name="pCylinder61_blinn3_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCylinder61_blinn3_0.geometry}
                    material={materials.blinn3}
                  />
                </group>
                <group
                  name="pCylinder62"
                  position={[-9.962, 16.181, 11.182]}
                  rotation={[0, Math.PI / 2, 0]}
                  scale={[0.725, 0.725, 0.617]}>
                  <mesh
                    name="pCylinder62_blinn3_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCylinder62_blinn3_0.geometry}
                    material={materials.blinn3}
                  />
                </group>
                <group
                  name="pCylinder63"
                  position={[9.832, 16.181, -1.93]}
                  rotation={[0, -Math.PI / 2, 0]}
                  scale={[0.725, 0.725, 0.617]}>
                  <mesh
                    name="pCylinder63_blinn3_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCylinder63_blinn3_0.geometry}
                    material={materials.blinn3}
                  />
                </group>
                <group
                  name="pCube134"
                  position={[0.907, 6.239, 8.442]}
                  scale={[0.341, 0.98, 0.964]}>
                  <mesh
                    name="pCube134_Small_Thingies_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube134_Small_Thingies_0.geometry}
                    material={materials.Small_Thingies}
                  />
                </group>
                <group
                  name="pCube135"
                  position={[0.316, 6.243, 8.442]}
                  scale={[0.341, 0.98, 0.964]}>
                  <mesh
                    name="pCube135_Small_Thingies_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube135_Small_Thingies_0.geometry}
                    material={materials.Small_Thingies}
                  />
                </group>
                <group name="pCube136" position={[-0.3, 6.23, 8.442]} scale={[0.341, 0.98, 0.964]}>
                  <mesh
                    name="pCube136_Small_Thingies_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube136_Small_Thingies_0.geometry}
                    material={materials.Small_Thingies}
                  />
                </group>
                <group
                  name="pCube137"
                  position={[-0.921, 6.23, 8.442]}
                  scale={[0.341, 0.98, 0.964]}>
                  <mesh
                    name="pCube137_Small_Thingies_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube137_Small_Thingies_0.geometry}
                    material={materials.Small_Thingies}
                  />
                </group>
                <group
                  name="pCube138"
                  position={[-1.498, 6.235, 8.442]}
                  scale={[0.341, 0.98, 0.964]}>
                  <mesh
                    name="pCube138_Small_Thingies_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube138_Small_Thingies_0.geometry}
                    material={materials.Small_Thingies}
                  />
                </group>
                <group name="aiSkyDomeLight1" position={[0.013, 0, 0]} />
                <group name="Rigging_03pCube1" />
                <group name="Rigging_03pCube3" />
                <group name="Rigging_03locator1" position={[0.005, -0.001, 8.645]} scale={0.364}>
                  <group name="Rigging_03transform1" position={[0, -0.092, 0]} scale={0.501}>
                    <group name="Object_336">
                      <primitive object={nodes._rootJoint} />
                      <skinnedMesh
                        name="Object_339"
                        geometry={nodes.Object_339.geometry}
                        material={materials.Rigging_03aiStandardSurface1}
                        skeleton={nodes.Object_339.skeleton}
                      />
                      <skinnedMesh
                        name="Object_341"
                        geometry={nodes.Object_341.geometry}
                        material={materials.Rigging_03lambert2}
                        skeleton={nodes.Object_341.skeleton}
                      />
                      <group name="Object_338" />
                      <group name="Object_340" />
                    </group>
                  </group>
                </group>
                <group name="Extra_Character_02pSphere1" />
                <group
                  name="Extra_Character_02locator1"
                  position={[-5.645, -0.569, 10.553]}
                  rotation={[-0.016, 0.695, 0.007]}
                  scale={[0.77, 0.824, 0.757]}>
                  <group name="Extra_Character_02transform1" scale={0.38}>
                    <group name="Object_373">
                      <primitive object={nodes._rootJoint_1} />
                      <skinnedMesh
                        name="Object_375"
                        geometry={nodes.Object_375.geometry}
                        material={materials.Extra_Character_02lambert2}
                        skeleton={nodes.Object_375.skeleton}
                      />
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

//useGLTF.preload('/spirited_away.glb')

export default SpiritedAway;
